blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions âœï¸
    url: https://github.com/HotCakeX/Harden-Windows-Security/discussions
    about: Please use GitHub discussions for any questions.
  - name: Basic FAQs ğŸ’
    url: https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions
    about: Answers to the Basic Frequently Asked Questions - Make sure to read them first.
  - name: AppControl Manager Privacy Policy ğŸ”’
    url: https://github.com/HotCakeX/Harden-Windows-Security/wiki/Privacy-Policy-for-the-AppControl-Manager
    about: The privacy policy for the AppControl Manager is available in this link.
