blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions âœï¸
    url: https://github.com/HotCakeX/Harden-Windows-Security/discussions
    about: Please use GitHub discussions for any questions.
  - name: Basic FAQs ğŸ’
    url: https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions
    about: Answers to the Basic Frequently Asked Questions
